update=16-04-2011 21:33:28
last_client=cvpcb
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[pcbnew]
[pcbnew/libraries]
LibName1=sockets
LibName2=connect
LibName3=discret
LibName4=pin_array
LibName5=divers
LibName6=libcms
LibName7=display
LibName8=valves
LibName9=led
LibName10=dip_sockets
LibName11=arports
LibName12=arshields
LibDir=D:\\BigBkp\\arCircuits\\arKicadLibs
